language: c
sudo: false
arch:
    - amd64
    - ppc64le
addons:
  apt:
    packages:
    - ocaml-nox
    - ocaml-findlib
    - portaudio19-dev

script: ./bootstrap && ./configure && make && make -C examples
